{% set version = "1.23-1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-dtw
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/dtw_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/dtw/dtw_{{ version }}.tar.gz
  sha256: 6ed6a3b52be673ce2617b8d48723c7c488c95aab88fe2912d7e00507838e826d

build:
  number: 3
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - {{ compiler('c') }}        # [unix]
    - {{ stdlib("c") }}          # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - {{ posix }}filesystem      # [win]
    - {{ posix }}make
    - {{ posix }}sed             # [win]
    - {{ posix }}coreutils       # [win]
    - {{ posix }}zip             # [win]
  host:
    - r-base
    - r-proxy

  run:
    - r-base
    - r-proxy

test:
  commands:
    - $R -e "library('dtw')"  # [not win]
    - "\"%R%\" -e \"library('dtw')\""  # [win]

about:
  home: http://dtw.r-forge.r-project.org/
  doc_url: https://dynamictimewarping.github.io
  license: GPL-2.0-only
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
  summary: A comprehensive implementation of dynamic time warping (DTW) algorithms in R.  DTW computes the optimal (least cumulative distance) alignment between points of two time series.  Common DTW variants covered include local (slope) and global (window) constraints, subsequence matches, arbitrary distance definitions,
    normalizations, minimum variance matching, and so on.  Provides cumulative distances, alignments, specialized plot styles, etc.
  license_family: GPL

extra:
  recipe-maintainers:
    - conda-forge/r
    - rvalieris
