travis:
  secure:
    BINSTAR_TOKEN: XI8WZ6Layy3exa8UOX/tPGwRfSofmgM7Jo+P/Jk7pQKimIZycV2N5mqeNf+YH1O5iimWqlhHccGj9gaJix2mEMW7IYbue4TpVJVS15563A4x5yKsFcP/HyXup3hp1kTuVKvjwgOavsRDJuh3jYlVEIUNToL6FgVeJc6J2wpPC8Jr9+md9l+C9zLiVlcldDVHkBSRWlIO+er2enGpBHFCqTxHLAxprWtPbRgIH36+B4rcDeENJC5RJHJLR0EsTtzAeFo2KNbVfB40XFM0VAkBA/VCUq1zj9RjK+dlbz5c79nncSLeJU2dhMz33enSUIoOhUjMj7MVQeNJaAJGRtk3oPxFKoQzjQpnVfLBT+cgc2egpr/n7mHdox9dAnD9MpMLVVBtnSxcKZ2VVs37FW6da60bmPxpcg8vzA3Rg86g6PjSddsKOehQB6jPaqqvtkFUihixr8vFuMXUs3TFQDr65Loc3FdgowKwBpse+dyJud7uusztZ05zPJ2lS+1S4SqezEEpAOS5SwBSs+R5FX1wwa1Tnx31hbpEia6zkE80jf5OwS+20s081dKCt6/C2qr/MCZwrj1D26BMRl0EvuvuNRKSiVKRTB5n/4sNa68TMLny6pZSzzcHGchYGIwdRBrSr6/h6TEVoYEBj1nRF2kx7ecf412m33w4cyf+i/OarsI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
